### ISSUE TITLE
Format of amount - comma or no comma by thousand

### ISSUE THREAD

**Issue by anderspeders** [NRGI/resourceprojects.org-frontend#101]
![format of amounts](https://cloud.githubusercontent.com/assets/1101585/8854877/414f62ba-3130-11e5-8422-6aadca9954e8.JPG)

**Comment by timgdavies** [comment]
Ok - so there are two parts to this issue:

* (1) The incoming data is incorrectly typed as strings, rather than numbers. I need to add better data type handling and conversion to taglifter;
* (2) We don't have a nice haanga filter for number formatting

So - for the moment we'll have to go with comma-free numbers to have consistency. 

We can do this in SPARQL for now, by using a replace statement in select to get rid of commas we do find. E.g.

```sparql
SELECT ?companyPayment ?payee_name ?currency (replace(?value,",","") as ?value) ?date ?year ?type WHERE {
}
```

I'll do this on the local__def__Company query, but will need to pick up synchronising this with other places tomorrow.

**Comment by anderspeders** [comment]
Great, comma free works!

We can add (1) to blue sky wish list.

**Comment by caprenter** [comment]
@timgdavies I can take this and make it consistent  across the site if you like

**Comment by timgdavies** [comment]
That would be great. Thanks @caprenter

**Comment by timgdavies** [comment]
We need to ensure all queries on the beta incorporate this.

**Comment by caprenter** [comment]
This is just a case of checking in the next day or so

**Comment by caprenter** [comment]
I'm confident this is uniform across the site. Please raise a ticket against anything find different
