### ISSUE TITLE
Front page design

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#15]
A frontpage wireframe for the site should be agreed with @anderspeders
A frontpage for the site should be implemented

**Comment by caprenter** [comment]
Currently we just have the Browse... options on the front page.

We need text etc, and maybe to restrict the browse options.

We also have 'internal errors' on many of the links due to the way lodspeakr handles default values.
e.g. http://lodspeakr.nrgi-dev.default.opendataservices.uk0.bigv.io/data/Ontology

**Comment by timgdavies** [comment]
This is still an issue to be address for the Beta.

**Comment by caprenter** [comment]
I'm not sure we have any agreement on what the front page should be showing as yet.
@timgdavies do you?

**Comment by davidmihalyi** [comment]
We had a few ideas for the frontpage, but these are non priority implementations:
-some headline counts about the scope of data on the frontpage: displaying how many projects, countries, companies we cover. (i understand count is currently broken)
-some updates on what new data is there 
-potentially some guided tours 

 But lets just have some token text for now.

Can you just put this text up for now?

Across the world, governments and companies are involved in natural resource projects, generating billions of dollars. The Natural Resource Governance Institute (NRGI) works to help people to realize the benefits of the endowments of oil, gas and minerals in their countries. Continued effort  in making the sector more transparent led to an increasing amount of information becoming available, but this information is currently underutilized partly due to difficulties and costs in accessing it. 

ResourceProjects.org (RP.org) is an open-source repository of data on oil, gas and mining projects across the world. It provides a platform to collect and search extractive project information using linked open data. It aims to harvest data on the location, status, associated contracts, companes, licenses from a variety of government and industry sources, as well as project-by-project payments to governments based on recent mandatory disclosure legislations in the EU, US and Canada. The platform will make it easier for journalists, CSOs, researchers and government officials to search, access and download relevant data originating from these various sources.

RP.org is a prototype under developement. Current data on the site is illustrative only, and no warranty of its accuracy or completeness is provided. RP.org is licensed under CC-BY-SA.

**Comment by timgdavies** [comment]
Thanks David - this text looks good - although I would suggest that publicly we avoid use of the RP.org abbreviation - as rp.org is not the domain - and to refer to it in that way is likely to create confusion (unless you want to buy rp.org, which is up for bids of $10k or above!)

**Comment by davidmihalyi** [comment]
Across the world, governments and companies are involved in natural resource projects, generating billions of dollars. The Natural Resource Governance Institute (NRGI) works to help people to realize the benefits of the endowments of oil, gas and minerals in their countries. Continued effort in making the sector more transparent led to an increasing amount of information becoming available, but this information is currently underutilized partly due to difficulties and costs in accessing it.

ResourceProjects.org is an open-source repository of data on oil, gas and mining projects across the world. It provides a platform to collect and search extractive project information using linked open data. It aims to harvest data on the location, status, associated contracts, companes, licenses from a variety of government and industry sources, as well as project-by-project payments to governments based on recent mandatory disclosure legislations in the EU, US and Canada. The platform will make it easier for journalists, CSOs, researchers and government officials to search, access and download relevant data originating from these various sources.

ResourceProjects.org is a prototype under developement. Current data on the site is illustrative only, and no warranty of its accuracy or completeness is provided. ResourceProjects.org is licensed under CC-BY-SA.

**Comment by davidmihalyi** [comment]
Thanks Tim!

**Comment by caprenter** [comment]
This is done
