### ISSUE TITLE
Status duplicates

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#182]
@timgdavies can you check out the status duplicates on this page pls?
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/project/PE/anta-rzaeth.html

The project seems to have 4 status (4 ids) that are the same.

**Comment by timgdavies** [comment]
This comes from around line 55 in the [Peru document](https://docs.google.com/spreadsheets/d/1gl3syhKsI-pR_lx3KykuKOLnHrp7ir2fRxjaPTO3DgM/edit#gid=141760938) which looks something like this:

| #project | #site      | #site+address | #commodity+commodityType | #commodity | #status+statusType | #status+trueAt | 
|----------|------------|---------------|--------------------------|------------|--------------------|----------------| 
| Antamina | San Marcos | Peru          | Mining                   | Copper     | Production         | 2014           | 
| Antamina | San Marcos | Peru          | Mining                   | Silver     | Production         | 2014           | 
| Antamina | San Marcos | Peru          | Mining                   | Lead       | Production         | 2014           | 
| Antamina | San Marcos | Peru          | Mining                   | Zinc       | Production         | 2014           | 

At the moment status is not related to commodity, just to project. So this ends up being read in as two separate sets of relationships: 

| #project | #site      | #site+address | #commodity+commodityType | #commodity | 
|----------|------------|---------------|--------------------------|------------| 
| Antamina | San Marcos | Peru          | Mining                   | Copper     | 
| Antamina | San Marcos | Peru          | Mining                   | Silver     | 
| Antamina | San Marcos | Peru          | Mining                   | Lead       | 
| Antamina | San Marcos | Peru          | Mining                   | Zinc       | 

and

| #project | #status+statusType | #status+trueAt | 
|----------|--------------------|----------------| 
| Antamina | Production         | 2014           | 
| Antamina | Production         | 2014           | 
| Antamina | Production         | 2014           | 
| Antamina | Production         | 2014           | 

which means some of these lines are redundant, and so creating the duplicates. 

For the time being, there are three approaches we could take:

(1) Remove the URI from the sparql query, so that DISTINCT is looking for distinct labels, and the different URIs get ignored;

(2) In the presentation layer, use a check for change in the loop. E.g. adding into the loop;

```
{%if lastSeenStatus != row.status.value %}
   {{ row.status.value }}
{% set lastSeenStatus = row.status.value %}
```
(3) Update the source file to remove the duplicate values.

I suspect (1) is the easiest response right now.

However, in the long-run we should check if this way of interpreting the model is correct:

@davidmihalyi is the current interpretation of the data against the model correct? Or should the model associate status also with commodity (i.e. to know that production started and stopped for different minerals at the site at a particular time)? In other words, are the four lines above redundant, or is each one saying something extra?

**Comment by davidmihalyi** [comment]
@timgdavies @carpenter yes, this correct. Only need to display where project ID, #status+statusType	#status+trueAt are distinct.

**Comment by caprenter** [comment]
This is done
