### ISSUE TITLE
Project title should not be optional on project lists

### ISSUE THREAD

**Issue by timgdavies** [NRGI/resourceprojects.org-frontend#198]
At the moment in queries on country page such as https://github.com/NRGI/resourceprojects.org-frontend/blob/master/components/types/local_def__Country/queries/projects.query the project title is optional.

With the way projects should come in, they should always have a name, and any projects without names, we don't want to display.

With an update to TagLifter to handle ID generation when names are missing we've ended up with a lot of orphan project records in the data, which are ending up displayed in these cases.

Updating the query should get rid of these from display - and we can look at cleaning the spreadsheets later to get rid of them from the data.

**Comment by caprenter** [comment]
There is already a  test to count the number of project table rows on the Angola page -this should work.

I've noticed there is now a problem where projects are counted elsewhere - e.g. country list page, but I have a fix and test in place for that. I'll share that elsewhere.

regarding the data, @timgdavies says it can be fixed in spreadsheets. Not sure where to make an issue of that
