### ISSUE TITLE
We may still get duplicate commodity Types

### ISSUE THREAD

**Issue by Bjwebb** [NRGI/resourceprojects.org-frontend#222]
https://github.com/NRGI/resourceprojects.org-frontend/blob/182-status-duplicates/components/types/local_def__Project/html.template#L62
(because this for loop is comparing to the last value, but the corresponding query isn't ordered).

So, we may get "Oil and Gas, Mining, Oil and Gas" instead of "Oil and Gas, Mining".

I don't currently know of any example projects that have both Commodity Types though, or in fact if any exist.

**Comment by caprenter** [comment]
I asked the question on Slack , and have been told that there are not any project with both commodityTupes so I'm less concerned for now - but I agree with your assessment

**Comment by davidmihalyi** [comment]
we now have duplicates due to lower case, upper case handled as distinct but valid inputs.

**Comment by timgdavies** [comment]
I've corrected the source data that was causing these duplicates.

The spreadsheet validation does not appear to always be case sensitive, which means that if someone types in 'oil' to a cell, rather than selects from the drop-down, we might get duplicates coming  through.

The way to fix is to look at Source to find where this is coming from, fix at source, and reload the data.
