### ISSUE TITLE
Lodspeakr max results (paging)

### ISSUE THREAD

**Issue by caprenter** [NRGI/resourceprojects.org-frontend#51]
Now there is a lot of data - lodspeakr max results on queries means we can't show all companies in a company list. 

Remove restriction? Paging? Show all?

**Comment by timgdavies** [comment]
I suggest we try to introduce paging, and, if possible, some sorting and filter options.

I believe paging might be about adding some optional parameters to queries, but haven't looked at this for a while...

**Comment by timgdavies** [comment]
From some investigation - I can't see anyway of passing a querystring into a LODSpeakr template. 

The variables that are made available to templates appear to be [set at Line 685 here](https://github.com/alangrafu/lodspeakr/blob/e0ce117e7596702e361be9194adda881362e0fff/classes/Utils.php#L685), so to get querystring content in via ?page=x looks like it would need modifications to LODSpeakr.

We could use {{lodspk.args.arg1|default:0}} in the limit section - e.g. 

```sparql
SELECT DISTINCT * WHERE {
    ?uri a rp:{{lodspk.args.arg0}}
    OPTIONAL { ?uri skos:prefLabel ?name }
}
ORDER BY (?name)
limit 50 OFFSET {{lodspk.args.arg1|default:0}} 
```

So that URLs of the form /data/Company/3 would fetch page 3 (with each page giving 50 values) or even data/Company/page/3 (using  {{lodspk.args.arg2|default:0}}).

However, it would be nicer to be able to offer a ?per-page and ?page type approach here - rather than using the URL path for pagination.

**Comment by timgdavies** [comment]
Ah - the other workaround here may be to create the variables we need via settings.php 

See the wiki [section on including your own variables](https://github.com/alangrafu/lodspeakr/wiki/Include-your-own-variables)

**Comment by timgdavies** [comment]
This looks promising - except I can't get the querystrings passed through to settings.php - I think due to the .htaccess rules.

I've had a quick look at http://simonecarletti.com/blog/2009/01/apache-rewriterule-and-query-string/ but not got my head around this yet

In theory, I think something like the following in settings.php should pass through what we need to paginate:

```php
$offset = 0;
if($_GET['offset']) {
    $offset = int($_GET['offset']);
}
$lodspk['offset'] = $offset;

$limit = 50;
if($_GET['limit']) {
    $limit = int($_GET['limit']);
}
$lodspk['limit'] = $limit;

$lodspk['next'] = $offset + $limit;
$lodspk['prev'] = $offset - $limit;

```

**Comment by anderspeders** [comment]
paging sounds great,

+1 on sorting and filtering

**Comment by timgdavies** [comment]
@caprenter Did you manage to make any progress on the .htaccess and paging issues? Let me know if anything more I should look into.

**Comment by Bjwebb** [comment]
I've set up the htaccess to pass the query string through. It should now be possible to use {{{{lodspk.offset}} etc. to implement pagination.

**Comment by caprenter** [comment]
So, we have some basic paging in place, but there is further work to be done here:
Get a count of full results
Show how many pages there are
Deal with next button, when there is no next!

**Comment by Bjwebb** [comment]
This is now fixed, except that pagination could be better, as described in https://github.com/NRGI/resourceprojects.org-frontend/issues/119
